---
- name: Create Inventory of CVE hosts
  hosts: localhost
  gather_facts: false

  vars:
   advisory_id: 

  vars_files:
    - insights

  tasks:

     - name: EDA | Insights | Retrieve related CVEs from Advisories
       ansible.builtin.uri:
        url: "https://console.redhat.com/api/patch/v3/advisories/{{ advisory_id }}/systems?page=1&perPage=20&sort=-last_upload&offset=0&limit=20"
        method: GET
        url_username: "{{ insights_username }}"
        url_password: "{{ insights_password }}"
        force_basic_auth: true
        status_code: 200
       register: cves_list

     - name: Extract display names
       ansible.builtin.set_fact:
         display_names: "{{ cves_list.json.data | map(attribute='attributes.display_name') | list }}"

     - name: display
       debug:
        msg: "{{ display_names }}"

     - name: Create Inventory
       ansible.controller.inventory:
        name: "Affected {{ advisory_id }} Hosts"
        organization: "Globo Financial Service"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"

     - name: Add hosts to AWX inventory
       ansible.controller.host:
        name: "{{ item }}"
        inventory: "Affected {{ advisory_id }} Hosts"
        state: present
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
       loop: "{{ display_names }}"
       when: display_names | length > 0
