---
- name: Send POST request to Red Hat API
  hosts: localhost

  vars:
   patch_advisory_id: 
   systems_list: 
   insights_remediation_name_reboot: RHSA-2024:4779

  vars_files:
   - insights

  tasks:
   - name: Create Remediation Project
     ansible.builtin.uri:
      url: https://console.redhat.com/api/remediations/v1/remediations
      method: POST
      status_code:
       - 200
       - 201
      headers:
       Content-Type: "application/json"
       accept: "application/json"
       Connection: "keep-alive"
      body: '{"name":"RHSA-2024:4779","add":{"issues":[{"id":"patch-advisory:RHSA-2024:4779","resolution":"fix","systems":["f3f01975-be31-47bb-9683-e9a37fc34f3d","272a6f58-9a03-4778-8031-ee64c1c63c5a"]}],"systems":[]},"auto_reboot":false}'
      return_content: true
      force_basic_auth: true
      url_username: "{{ insights_username }}"
      url_password: "{{ insights_password }}"
     register: insights_remediation

   - name: Create Remediation Playbook
     ansible.builtin.uri:
      url: https://console.redhat.com/api/remediations/v1/playbook
      method: POST
      status_code:
       - 200
       - 201
      headers:
       Content-Type: "application/json"
       accept: "application/json"
       Connection: "keep-alive"
      body: '{"issues":[{"id":"patch-advisory:RHSA-2024:4779","systems":["272a6f58-9a03-4778-8031-ee64c1c63c5a","f3f01975-be31-47bb-9683-e9a37fc34f3d"]}]}'
      return_content: true
      force_basic_auth: true
      url_username: "{{ insights_username }}"
      url_password: "{{ insights_password }}"

   - name: Normalize playbook name to create job template
     ansible.builtin.set_fact:
      job_template_playbook: "{{ insights_remediation.json.id }}.yml"

  
   - name: Update Insights Repo
     ansible.controller.project_update:
      project: "Infrastructure-Insights"
      timeout: 5
      controller_host: "{{ controller_host }}"
      controller_username: "{{ controller_username }}"
      controller_password: "{{ controller_password }}"

   - name: playbook
     debug:
      msg: "{{ job_template_playbook }}"
      
   - name: Generate job template with the generated playbook
     ansible.controller.job_template:
      name: "Remediate CVE"
      validate_certs: false
      job_type: "run"
      organization: "Globo Financial Service"
      inventory: "Affected RHSA-2024:4779 Hosts"
      project: "Infrastructure-Insights"
      playbook: "{{ job_template_playbook }}"
      credentials:
        - "SC4-Rhel"
      controller_host: "{{ controller_host }}"
      controller_username: "{{ controller_username }}"
      controller_password: "{{ controller_password }}"
      state: "present"

   - name: Create workflow template for approval
     ansible.controller.workflow_job_template:
      controller_host: "{{ controller_host }}"
      controller_username: "{{ controller_username }}"
      controller_password: "{{ controller_password }}"
      validate_certs: false
      organization: "Globo Financial Service"
      name: "CVE remediation workflow"
      inventory: "Affected RHSA-2024:4779 Hosts"

        # - name: EDA | Insights | Add approval node for workflow
        #   ansible.controller.workflow_job_template_node:
        #     controller_host: "{{ lookup('env', 'CONTROLLER_HOST') }}"
        #     controller_username: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
        #     controller_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
        #     validate_certs: false
        #     organization: Default
        #     workflow_job_template: "[Insights] {{ hostvars[inventory_hostname].ansible_host }}  CVE remediation workflow"
        #     identifier: cve-workflow-approval-reboot
        #     approval_node:
        #       description: "CVE remediation requires reboot, proceed?"
        #       name: cve-reboot-approval
        #       timeout: 3600

        # - name: EDA | Insights | Add remediation node for workflow
        #   ansible.controller.workflow_job_template_node:
        #     controller_host: "{{ lookup('env', 'CONTROLLER_HOST') }}"
        #     controller_username: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
        #     controller_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
        #     validate_certs: false
        #     organization: Default
        #     workflow_job_template: "[Insights] {{ hostvars[inventory_hostname].ansible_host }}  CVE remediation workflow"
        #     identifier: cve-remediation-reboot
        #     unified_job_template: "[Insights] Remediate CVE on {{ hostvars[inventory_hostname].ansible_host }} - Reboot required"

        # - name: EDA | Insights | Link remediation and approval node
        #   ansible.controller.workflow_job_template_node:
        #     controller_host: "{{ lookup('env', 'CONTROLLER_HOST') }}"
        #     controller_username: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
        #     controller_password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
        #     validate_certs: false
        #     organization: Default
        #     workflow_job_template: "[Insights] {{ hostvars[inventory_hostname].ansible_host }}  CVE remediation workflow"
        #     identifier: cve-workflow-approval-reboot
        #     success_nodes:
        #       - cve-remediation-reboot
