---
- name: RHEL - Inject CVE-2024-4032
  hosts: python_cve_targets
  gather_facts: true
  become: true

  tasks:

   - name: Inject Python vulnerability -
     ansible.builtin.yum:
      name: python3-3.9.18-3.el9.x86_64
      state: present
      allow_downgrade: true

   - name: Perform initial Insights upload
     ansible.builtin.command: >
      /bin/insights-client
     register: __insights_scan
     changed_when: __insights_scan.rc == 0

   - name: Run malware scan initial config
     ansible.builtin.command: >
      /bin/insights-client --collector malware-detection
     register: __malware_scan
     changed_when: __malware_scan.rc == 0
