---
- name: Send POST request to Red Hat API
  hosts: localhost

  vars:
   patch_advisory_id: 
   systems_list: 
   insights_remediation_name_reboot: "CVE RHSA-20244779"

  vars_files:
   - insights

  tasks:

    - name: Retrieve related CVEs from Advisories
      ansible.builtin.uri:
       url: "https://console.redhat.com/api/patch/v3/advisories/{{ advisory_id }}/systems?page=1&perPage=20&sort=-last_upload&offset=0&limit=20"
       method: GET
       url_username: "{{ insights_username }}"
       url_password: "{{ insights_password }}"
       force_basic_auth: true
       status_code: 200
      register: cves_list

    - name: Extract display names
      ansible.builtin.set_fact:
        display_names: "{{ cves_list.json.data | map(attribute='attributes.display_name') | list }}"

    - name: Create Inventory
      ansible.controller.inventory:
       name: "Affected {{ advisory_id }} Hosts"
       organization: "Globo Financial Service"
       state: present
       controller_host: "{{ controller_host }}"
       controller_username: "{{ controller_username }}"
       controller_password: "{{ controller_password }}"

    - name: Add hosts to AWX inventory
      ansible.controller.host:
       name: "{{ item }}"
       inventory: "Affected {{ advisory_id }} Hosts"
       state: present
       controller_host: "{{ controller_host }}"
       controller_username: "{{ controller_username }}"
       controller_password: "{{ controller_password }}"
      loop: "{{ display_names }}"
      when: display_names | length > 0

    - name: Create Remediation Project
      ansible.builtin.uri:
       url: https://console.redhat.com/api/remediations/v1/remediations
       method: POST
       status_code:
        - 200
        - 201
       headers:
        Content-Type: "application/json"
        accept: "application/json"
        Connection: "keep-alive"
       body: '{"name":"CVE RHSA-20244779","add":{"issues":[{"id":"patch-advisory:RHSA-2024:4779","resolution":"fix","systems":["f3f01975-be31-47bb-9683-e9a37fc34f3d","272a6f58-9a03-4778-8031-ee64c1c63c5a"]}],"systems":[]},"auto_reboot":false}'
       return_content: true
       force_basic_auth: true
       url_username: "{{ insights_username }}"
       url_password: "{{ insights_password }}"
      register: insights_remediation

    - name: Create Remediation Playbook
      ansible.builtin.uri:
       url: https://console.redhat.com/api/remediations/v1/playbook
       method: POST
       status_code:
        - 200
        - 201
       headers:
        Content-Type: "application/json"
        accept: "application/json"
        Connection: "keep-alive"
       body: '{"issues":[{"id":"patch-advisory:RHSA-2024:4779","systems":["272a6f58-9a03-4778-8031-ee64c1c63c5a","f3f01975-be31-47bb-9683-e9a37fc34f3d"]}]}'
       return_content: true
       force_basic_auth: true
       url_username: "{{ insights_username }}"
       url_password: "{{ insights_password }}"

    - name: Normalize playbook name to create job template
      ansible.builtin.set_fact:
       job_template_playbook: "{{ insights_remediation_name_reboot | lower | replace(' ', '-') | replace('.','') | regex_replace('-{2,}', '-') }}-{{ insights_remediation.json.id }}.yml"
  
    - name: Update Insights Repo
      ansible.controller.project_update:
       project: "Infrastructure-Insights"
       timeout: 5
       controller_host: "{{ controller_host }}"
       controller_username: "{{ controller_username }}"
       controller_password: "{{ controller_password }}"

    - name: playbook
      debug:
       msg: "{{ job_template_playbook }}"
      
    - name: Generate job template with the generated playbook
      ansible.controller.job_template:
       name: "SC4 - CVE RHSA-20244779 Remediation"
       validate_certs: false
       job_type: "run"
       organization: "Globo Financial Service"
       inventory: "Affected RHSA-2024:4779 Hosts"
       project: "Infrastructure-Insights"
       playbook: "{{ job_template_playbook }}"
       credentials:
         - "SC4-Rhel"
       controller_host: "{{ controller_host }}"
       controller_username: "{{ controller_username }}"
       controller_password: "{{ controller_password }}"
       state: "present"

    - name: Create workflow template for approval
      ansible.controller.workflow_job_template:
       controller_host: "{{ controller_host }}"
       controller_username: "{{ controller_username }}"
       controller_password: "{{ controller_password }}"
       validate_certs: false
       organization: "Globo Financial Service"
       name: "SC4 CVE RHSA-20244779 Remediation Workflow"
       inventory: "Affected RHSA-2024:4779 Hosts"

    - name: Add approval node for workflow
      ansible.controller.workflow_job_template_node:
       controller_host: "{{ controller_host }}"
       controller_username: "{{ controller_username }}"
       controller_password: "{{ controller_password }}"
       validate_certs: false
       organization: "Globo Financial Service"
       workflow_job_template: "SC4 CVE RHSA-20244779 Remediation Workflow"
       identifier: cve-approval
       approval_node:
         description: "Would you like to remediate affected systems?"
         name: cve-approval
         timeout: 3600

    - name: Add remediation node for workflow
      ansible.controller.workflow_job_template_node:
       controller_host: "{{ controller_host }}"
       controller_username: "{{ controller_username }}"
       controller_password: "{{ controller_password }}"
       validate_certs: false
       organization: "Globo Financial Service"
       workflow_job_template: "SC4 CVE RHSA-20244779 Remediation Workflow"
       identifier: cve-remediation
       unified_job_template: "SC4 - CVE RHSA-20244779 Remediation"

    - name: Link remediation and approval node
      ansible.controller.workflow_job_template_node:
       controller_host: "{{ controller_host }}"
       controller_username: "{{ controller_username }}"
       controller_password: "{{ controller_password }}"
       validate_certs: false
       organization: "Globo Financial Service"
       workflow_job_template: "SC4 CVE RHSA-20244779 Remediation Workflow"
       identifier: cve-approval
       success_nodes:
         - cve-remediation
