---
- hosts: localhost
  gather_facts: false
  connection: httpapi
  vars:
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    SN_HOST:
    SN_USERNAME:
    SN_PASSWORD:
    advisory_id:
    incident_number:


  vars_files:
   - insights
    
  tasks:

   - name: Gather CVE details
     ansible.builtin.uri:
       url: "https://console.redhat.com/api/patch/v3/advisories/RHSA-2024:4779"
       method: GET
       url_username: "{{ insights_username }}"
       url_password: "{{ insights_password }}"
       force_basic_auth: true
       status_code: 200
     register: cve_details

   - name: Retrieve related CVEs from Advisories
     ansible.builtin.uri:
      url: "https://console.redhat.com/api/patch/v3/advisories/{{ advisory_id }}/systems?page=1&perPage=20&sort=-last_upload&offset=0&limit=20"
      method: GET
      url_username: "{{ insights_username }}"
      url_password: "{{ insights_password }}"
      force_basic_auth: true
      status_code: 200
     register: cves_list

   - name: Extract display names
     ansible.builtin.set_fact:
       affected_systems: "{{ cves_list.json.data | map(attribute='attributes.display_name') | list }}"

   - name: Extract type
     ansible.builtin.set_fact:
       cve_type: "{{ cve_details.json.data.attributes.advisory_type_name }}"
      
   - name: Extract cve
     ansible.builtin.set_fact:
       cves: "{{ cve_details.json.data.attributes.cves }}"

   - name: Extract Severityity
     ansible.builtin.set_fact:
       sev: "{{ cve_details.json.data.attributes.severity }}"

   - name: Extract description
     ansible.builtin.set_fact:
       cves_description: "{{ cve_details.json.data.attributes.description }}"

   - name: Extract Insights URL
     ansible.builtin.set_fact:
       insights_url: "{{ cve_details.json.data.attributes.description }}"

   - name: Extract Solution
     ansible.builtin.set_fact:
       solution: "{{ cve_details.json.data.attributes.solution }}"

   - name: Extract Topic
     ansible.builtin.set_fact:
       topic: "{{ cve_details.json.data.attributes.topic }}"

   - name: Log Change request
     servicenow.itsm.change_request:
      instance:   
       host: "{{ SN_HOST }}"
       username: "{{ SN_USERNAME }}"
       password: "{{ SN_PASSWORD }}"
      type: normal
      risk: moderate
      assignment_group: "Change Management"
      state: assess
      short_description: Vulnerabilities detected - Remediation needed
      description: |

        Affected systems: "{{ affected_systems }}"

        CVE Description: "{{ cves_description }}"
        Insights URL: "{{ insights_url }}"
       
     register: new_change_request


   - name: Create incident
     servicenow.itsm.incident:
      instance:
       host: "{{ SN_HOST }}"
       username: "{{ SN_USERNAME }}"
       password: "{{ SN_PASSWORD }}"
      state: new
      caller: "{{ lookup('env', 'SN_USERNAME') }}"
      short_description: New Advisory CVE Type - "{{ cve_type }}" Affected systems - "{{ affected_systems }}"
      description: |
      
        Change Request Logged: "{{ new_change_request.record.number }}"

        Alert Type: "{{ cve_type }}"  CVE:  "{{ cves }}"
        Incident Topic: "{{ topic }}"

        Affected systems: "{{ affected_systems }}"

        CVE Description: "{{ cves_description }}"
        Insights URL: "{{ insights_url }}"

        Possible Solution: "{{ solution }}"

        Change Request: "{{ new_change_request.record.number }}"

      impact: high
      urgency: high
     register: new_change_request
     delegate_to: localhost

   - name: Extract Record
     ansible.builtin.set_fact:
       incident_number: "{{ new_change_request.record.number }}"
       cacheable: true
       
